# Generated by Django 2.2.13 on 2020-10-12 23:50

from django.db import migrations, models
import django.db.models.deletion
import esite.home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('city', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('copyrightholder', models.CharField(blank=True, max_length=255, null=True)),
                ('about', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('privacy', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('shipping', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('gtc', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('cancellation_policy', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('sociallinks', wagtail.core.fields.StreamField([('link', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz'))], blank=True, null=True)),
                ('headers', wagtail.core.fields.StreamField([('h_hero', wagtail.core.blocks.StructBlock([('slide_image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Großes, hochauflösendes Titelbild', required=True)), ('slide_head', wagtail.core.blocks.CharBlock(help_text='Titlebild-Text', required=False)), ('slide_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button, help_text='Titelbild-Button', required=False))], icon='image'))])),
                ('sections', wagtail.core.fields.StreamField([('s_feature', wagtail.core.blocks.StructBlock([('features', wagtail.core.blocks.StreamBlock([('feature', wagtail.core.blocks.StructBlock([('feature_image', wagtail.images.blocks.ImageChooserBlock(help_text='Icon, um eine angebotene Leistung darzustellen', required=True)), ('feature_head', wagtail.core.blocks.CharBlock(help_text='Titel einer angebotenen Leistung', required=False)), ('feature_text', wagtail.core.blocks.RichTextBlock(help_text='Beschreibung der angebotenen Leistung', label='Text', required=True))], blank=False, icon='fa-info', null=True, required=False))], help_text='Füge zwischen einer und drei angebotenen Leistungen hinzu', max_num=3, null=True, required=True))], icon='fa-info')), ('s_maps', wagtail.core.blocks.StructBlock([('coordinates', wagtail.core.blocks.StreamBlock([('coordinate', wagtail.core.blocks.StructBlock([('coordinate', wagtail.core.blocks.CharBlock(help_text='Gebe hier die Google-Maps-Koordinaten eines Projektes an', required=True))], icon='fa-info', required=False))], help_text='Zeige die Projekt-Locations in einer Map an', required=True))], icon='fa-info')), ('s_partners', wagtail.core.blocks.StructBlock([('coordinates', wagtail.core.blocks.StreamBlock([('coordinate', wagtail.core.blocks.StructBlock([('coordinate', wagtail.core.blocks.CharBlock(help_text='Gebe hier die Google-Maps-Koordinaten eines Projektes an', required=True))], icon='fa-info', required=False))], help_text='Liste hier Partnerunternehmen auf', required=True))], icon='fa-info')), ('s_references', wagtail.core.blocks.StructBlock([('ref', wagtail.core.blocks.StreamBlock([('reference', wagtail.core.blocks.StructBlock([('ref_img', wagtail.images.blocks.ImageChooserBlock(help_text='Referenz-Titelbild', required=True)), ('ref_link', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button, help_text='Referenz-Unterseite', required=False)), ('ref_head', wagtail.core.blocks.CharBlock(help_text='Referenz-Header', required=False)), ('ref_lead', wagtail.core.blocks.CharBlock(help_text='Referenz-Untertitel', required=False))], icon='fa-info', required=False))], help_text='Referenzen', required=True))], icon='fa-info')), ('s_about', wagtail.core.blocks.StructBlock([('about_img', wagtail.images.blocks.ImageChooserBlock(help_text='Portraitfoto', required=False)), ('about_head', wagtail.core.blocks.CharBlock(help_text='Über mich-Header', required=False)), ('about_lead', wagtail.core.blocks.CharBlock(help_text='Untertitel', required=False)), ('about_text', wagtail.core.blocks.RichTextBlock(help_text='Beschreibung Über Mich', label='Text', required=True))], icon='fa-info')), ('s_news', wagtail.core.blocks.StructBlock([('news', wagtail.core.blocks.StreamBlock([('news', wagtail.core.blocks.StructBlock([('news_img', wagtail.images.blocks.ImageChooserBlock(help_text='News-Titelbild', required=True)), ('news_head', wagtail.core.blocks.CharBlock(help_text='News-Header', required=False)), ('news_text', wagtail.core.blocks.RichTextBlock(help_text='Kurze Beschreibung der News', label='Text', required=True))], icon='fa-info', required=False))], help_text='Neuigkeiten zu Projekten', required=True))], icon='fa-info')), ('s_contentcenter', wagtail.core.blocks.StructBlock([('content_center_head', wagtail.core.blocks.CharBlock(help_text='Content-Center Header', required=False)), ('content_center_lead', wagtail.core.blocks.CharBlock(help_text='Content-Center Untertitel', required=False)), ('content_center_text', wagtail.core.blocks.RichTextBlock(help_text='Content-Center Text', label='Text', required=False))], icon='fa-info')), ('s_contentright', wagtail.core.blocks.StructBlock([('content_right_img', wagtail.images.blocks.ImageChooserBlock(help_text='Content-Right Titelbild', required=False)), ('content_right_head', wagtail.core.blocks.CharBlock(help_text='Content-Right Header', required=False)), ('content_right_lead', wagtail.core.blocks.CharBlock(help_text='Content-Right Untertitel', required=False)), ('content_right_text', wagtail.core.blocks.RichTextBlock(help_text='Content-Right Text', label='Text', required=False))], icon='fa-info')), ('s_contentleft', wagtail.core.blocks.StructBlock([('content_left_img', wagtail.images.blocks.ImageChooserBlock(help_text='Content-Left Titelbild', required=False)), ('content_left_head', wagtail.core.blocks.CharBlock(help_text='Content-Left Header', required=False)), ('content_left_lead', wagtail.core.blocks.CharBlock(help_text='Content-Left Untertitel', required=False)), ('content_left_text', wagtail.core.blocks.RichTextBlock(help_text='Content-Left Text', label='Text', required=False))], icon='fa-info'))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_title', models.CharField(max_length=255, null=True)),
                ('button_embed', models.CharField(blank=True, max_length=255, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('button_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
        ),
    ]
