# Generated by Django 2.2.13 on 2020-10-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20201012_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='link',
        ),
    ]
